### ISSUE TITLE
Improve code reuse in mirror node client

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [LimeChain/hedera-eth-bridge-validator#140]
In the mirror node client -> `GetAccountCreditTransactionsBetween` and `GetMessagesForTopicBetween` there is a piece of code that is duplicated: `iterating over array of objects and filtering if their `ConsensusTimestamp` < than `to`.

Introduce new `array` helper. Pseudo-code:
```Go
// Filter filters a given array based on a provided filter function
func Filter(arr []interface{}, test func(interface{}) bool) (res []interface{}) {
	for _, e := range arr {
		if test(e) {
			res = append(res, e)
		}
	}
	return
}
```

**Comment by georgiyazovaliiski** [comment]
I am not sure over-generalizing is a good idea in GO.
