### ISSUE TITLE
Fee Calculator for CryptoTransfer Event Handler

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [LimeChain/hedera-eth-bridge-validator#15]
1. Sanity Check
Implement the `fee-calculator.go` to validate that the amount that is being transferred is `transferAmount > txFee + serviceFee`, where `txFee` is set in the crypto transfer memo and `serviceFee` is the fee set in the smart contract

2. Fee Estimator
- Add exchange rate service that updates the HBAR/ETH price every 1 hour from external API
- Store the exchange rate in a Postgres DB
- every time a new request is triggered, and `ValidateExecutionFee` is called:
1) perform a sanity check of the fee `(1)`
2) Get the `gasPrice` from the encoded `gasPrice` in the crypto transfer memo
3) using the estimated gas usage and `gas price`, calculate the required `eth` for the TX
4) Using the `ETH/HBAR` exchange rate, calculate the `txFee` in HBARS
5) Validate that the `txFee >= estimated HBAR fee`

3. Implement Unit tests for the fee calculator

**Comment by failfmi** [comment]
Information about ETH gas:
https://ethereum.org/en/developers/docs/gas/
https://defiprime.com/gas

For step 4., create a `go` client file that fetches the current price of `HBAR/ETH` using Coingecko API  https://www.coingecko.com/api/documentations/v3
Coin id is `hedera-hashgraph`.
