### ISSUE TITLE
Create new repository with the smart contracts

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [LimeChain/hedera-eth-bridge-validator#48]
- Create new repository containing the smart contracts of the Bridge -> WHBAR token + Bridge Contract
- Add deployment script that can be executed easily so that anyone can deploy the set Token/Bridge contracts that he needs for local development

**Comment by failfmi** [comment]
There is already an existing one [here](https://github.com/LimeChain/hedera-eth-bridge-contracts).
