### ISSUE TITLE
Gnosis Multisig

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [LimeChain/hedera-eth-bridge-validator#52]
- Deploy Gnosis MultiSig managed by `3` custodians on Test Environment
- Use the Gnosis safe to deploy the `bridge contract` and the `WHBAR` token
- Test the use-case for adding new custodians

**Comment by Holymir** [comment]
Rinkeby address - 0x785c864b9F3Cf790478c3473B86FBA6BD75A6365
