### ISSUE TITLE
Verify DB records after E2E execution

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [LimeChain/hedera-eth-bridge-validator#75]
- Implement a DB verification service inside the `e2e` folder.
- The service must be able to easily assert that a given record exists in the DB. 
- The service could be using the already implemented repositories for the validator node

We would like to ideally be able to:
- verify that a record is created by the`TransactionRepo` and it has the correct properties at the end of the execution 
- verify that there are TransactionMessage records created by the `MessageRepo` and all of them have correct properties at the end of the execution.

**Comment by failfmi** [comment]
An additional read-only user for the db might be needed.
